spring:
  application:
    name: grpc-client

grpc:
  client:
    greet-service:
      negotiationType: PLAINTEXT
      address: "static://localhost:9090"
      enableKeepAlive: true
      keepAliveWithoutCalls: true
